### ISSUE TITLE
Where should dashboards.yaml be placed?

### ISSUE THREAD

**Issue by kaiwei** [andreasgerstmayr/fava-dashboards#1]
For the life of me, I can't figure out where to place the configuration document.

Josh

**Comment by andreasgerstmayr** [comment]
Hi @kaiwei!

The configuration should be in the same directory where Fava is started. For example if you run `fava personal.beancount`, the `dashboards.yaml` file should be in the same directory as `personal.beancount`.

I've updated the README to clarify this, and also to mention a way to customize the location of the configuration file.
