### ISSUE TITLE
Repurpose shared Javascript function across panels

### ISSUE THREAD

**Issue by addisonklinke** [andreasgerstmayr/fava-dashboards#14]
I've written a few helper functions to post-process the BQL results into the format I want for e-charts. Would it be feasible to have a separate JS file containing these that can be included in the YAML on a per-panel basis? I think this has a few benefits
1. Reduce code duplication
2. Allow viewing/editing JS with proper syntax highlighting
3. Enable unit testing of JS functions (currently I add assertions to my `script`, but this increases runtime unnecessarily)

**Comment by andreasgerstmayr** [comment]
Yeah, I think having a `dashboards.js` next to the `dashboards.yaml` which common helper functions would be a nice addition.

Can you give #15 a try? It loads a file `dashboards.js` in the same directory as `dashboards.yaml`, and all functions declared there are accessible in every panel.
