### ISSUE TITLE
Portfolio gains panel

### ISSUE THREAD

**Issue by scanta2** [andreasgerstmayr/fava-dashboards#2]
Awesome work!
Question.
If I add a time condition (e.g., `year > 2017`) in the `bql` query for the Portfolio Gains panel, the gains are "translated" so they start at roughly $0 for the first sample.
`
SELECT year, month, CONVERT(LAST(balance), '{{fava.ccy}}') AS market_value, COST(LAST(balance)) AS book_value
WHERE year > 2017 AND account ~ 'Assets:' AND currency != '{{fava.ccy}}'
GROUP BY year, month
`
vs
`
SELECT year, month, CONVERT(LAST(balance), '{{fava.ccy}}') AS market_value, COST(LAST(balance)) AS book_value
WHERE account ~ 'Assets:' AND currency != '{{fava.ccy}}'
GROUP BY year, month
`

Not adding the time condition makes the query run very slowly for me, as I have data as far back as 1994...

**Comment by andreasgerstmayr** [comment]
Can you try the following?
```
SELECT year, month, CONVERT(LAST(balance), '{{fava.ccy}}') AS market_value, COST(LAST(balance)) AS book_value
FROM OPEN ON 2018-01-01
WHERE account ~ 'Assets:' AND currency != '{{fava.ccy}}' GROUP BY year, month
```

**Comment by scanta2** [comment]
That worked as expected!
Just so I understand, what's the difference between the two queries?

Thanks

**Comment by andreasgerstmayr** [comment]
I'm not an expert in BQL, but I think `WHERE year > 2017` basically filters out all transactions before that year, like if your ledger was empty before this date. Then the account balances don't add up. The `OPEN AT` query on the other hand sums up the entries before that year instead of ignoring them.

The `OPEN AT` syntax is described in this document: https://beancount.github.io/docs/beancount_query_language.html#opening-a-period

**Comment by scanta2** [comment]
@andreasgerstmayr I am giving this more thought, and I still do not think this query is doing what it is supposed to do. It looks like the conversion is happening every month, but with the latest price, not with the price at the time indicated by the time axis.

**Comment by andreasgerstmayr** [comment]
@scanta2: thank you so much for raising this issue!

You're right, the price conversion was wrong, exactly as you described. I've updated the dashboards to convert the price at the time of the last transaction of a specific month. Can you confirm that the chart is correct now?

**Comment by scanta2** [comment]
> @scanta2: thank you so much for raising this issue!
> 
> You're right, the price conversion was wrong, exactly as you described. I've updated the queries to convert the price at the time of the last transaction of a specific month. Can you confirm that the chart shows correct values now?

@andreasgerstmayr Thank you, the chart is plotting the correct values now.
