### ISSUE TITLE
fava-dashboards unable to import 'simple_units' 

### ISSUE THREAD

**Issue by NoGare** [andreasgerstmayr/fava-dashboards#20]
Fava Version: 1.26
Python Version: 3.10.12

Following the installation instruction by pulling the most up to date version of fava-dashboards directly from github, the following error is reported within fava when running the example files(example.beancount & dashboards.yaml). Any recommendations on how to further debug the issue or a resolution? 

```

Importing module "fava_dashboards" failed.
Error: "cannot import name 'simple_units' from 'fava.core.conversion' (/usr/local/lib/python3.10/dist-packages/fava/core/conversion.py)"
```

Thank you in advance for your time;

Regards -

**Comment by andreasgerstmayr** [comment]
Hi @NoGare, I updated the code today to use a feature from Fava 1.26.1, but unfortunately I forgot to update the version requirements.

Can you try updating your Fava version to 1.26.1?
