### ISSUE TITLE
Feature Requested: Support ninja template in link field

### ISSUE THREAD

**Issue by ileodo** [andreasgerstmayr/fava-dashboards#23]
1. in dashboard.yaml, have a map allows user to define some variables, e.g. "fava_path" describing the fava url path
2. allow users to refer to those variables in fields like `link`, e.g. `{{fava_path]}/account/ABC`

**Comment by andreasgerstmayr** [comment]
I'd like to keep this extension as simple as possible and would rather not support templating.
To preprocess your `dashboards.yaml` file you can use for example `envsubst`: https://dustinrue.com/2020/05/simplistic-templating-with-envsubst/
