### ISSUE TITLE
Optionally trim sankey start date

### ISSUE THREAD

**Issue by AlphaJack** [andreasgerstmayr/fava-dashboards#25]
Hi Andreas, thank you for this wonderful Fava extension.

I started using Fava/beancount way before my first job.
Therefore, the figures I see are way different from the reality of the last 9 months.
I would like to trim the Sankey diagram to the last 9 months, to get a realistic overview of my saving rate and recent expenses.

If I specify a date, it should be used in both the query and the `days` calculation. If I only add it to the query, `days` still reports the number of days since my very first transaction, way before 9 months ago.

My solution is to:

- add `AND date > 2023-02-01`  to the query
- replace  `new Date(ledger.dateFirst)` with `new Date("2023-02-01")`

Is it possible to specify the date once as a parameter of the query, the JS code and maybe also the title?
Related to #23

**Comment by andreasgerstmayr** [comment]
hi @AlphaJack, can you use the fava time filter (in the top bar) for it?
When you specify `month-8 - month` it should give you the results you want, without any modification of the sankey chart.

Personally I'm using this shortcut to show the last 12 months (excl. the current month, as I usually don't have up-to-date data for the current month):
```
1992-01-01 custom "fava-sidebar-link" "Last 12 months" "/jump?time=month-12 - month-1&interval=month"
```

**Comment by AlphaJack** [comment]
Thank you, this is even more versatile!
