### ISSUE TITLE
Historical net worth allocation

### ISSUE THREAD

**Issue by AlphaJack** [andreasgerstmayr/fava-dashboards#26]
Hi, I would like to suggest an historical net worth allocation chart, but I am not sure how to implement it.

We already have an historical income and expense stacked bar chart,
![image](https://github.com/andreasgerstmayr/fava-dashboards/assets/19962243/55925e71-6aaf-490e-bb22-a99011874837)

and I think it could be repurposed for assets and liabilities.

![image](https://github.com/andreasgerstmayr/fava-dashboards/assets/19962243/054ac7be-6c0a-45b4-ad51-924b4b205ee6)

For the latter I had to take snapshots of the amounts in the "Assets Allocation" chart at 31st December of 2021, 2022 and 2023. I then used a csv file, `pandas` and `matplotlib` to group and plot the values.

I like your implementation of the stacked bar chart, as liabilities could appear as a second stack for each period.
I know you grouped income and expenses by year and month, but I guess this cannot be done so easily for assets and liabilities.

Can we have such a chart?

**Comment by andreasgerstmayr** [comment]
I like the idea. It's basically the inner circle of the "Asset Classes" chart, grouped by year.
It shouldn't be too difficult to implement, afaics we can use the query and asset classification code from the "Asset Classes" chart and group by year (or year and month? but I guess grouping by year only makes more sense).
