### ISSUE TITLE
How to add multiple dashboards?

### ISSUE THREAD

**Issue by pallavg** [andreasgerstmayr/fava-dashboards#27]
Hi - I would like to know if it is possible to add multiple dashboards to the same beancount ledger? If so, how to accomplish that. I am able to add a single dashboard and it runs fine. Thanks for the great extension.

**Comment by flyaway1217** [comment]
Yeah. I wonder the same thing. It would be nice to allow multiple yaml files.

**Comment by andreasgerstmayr** [comment]
Hi, as far as I know this is not possible, because the same Fava extension cannot be loaded twice, and a Fava extension can only have one report (link in the sidebar).
See also the discussion in #7
