### ISSUE TITLE
Load the plugin twice and change name

### ISSUE THREAD

**Issue by francocalvo** [andreasgerstmayr/fava-dashboards#7]
Hi! I'm starting to use the plugin and it's awesome to create custom reports for my monthly expenses, etc. 

I'd like to be able to load the plugin twice, as to have two tabs in Fava. In my case, I have to track most things twice, in my home currency, which is very volatile, and in dollars. This would allow me to duplicate most dashboards but changing the currency.

Maybe this is better suited for the Fava repo, but also I think, doing something like this would work perfectly and be very flexible:

```
2023-01-02 custom "fava-extension" "fava_dashboards" "[ 
    {'config': 'plugins/fava_dashboards/example01.yaml', name: "Dashboards 01"}, 
    {'config': 'plugins/fava_dashboards/example02.yaml', name: "Dashboards 02"}
]"
```

**Comment by andreasgerstmayr** [comment]
afaics that's currently not possible, because each Fava extension has only one entry in the navigation bar and the name of the navigation entry is static. You can open an issue in the Fava repo, or alternatively add multiple dashboards in the same file and for example prefix them with the currency.

**Comment by francocalvo** [comment]
Mhmm. Reading a bit about other plugins, I think you are right about it not being possible. Bummer. 

About your workaround, could you show me a little example on what you mean?

**Comment by andreasgerstmayr** [comment]
> About your workaround, could you show me a little example on what you mean?

You can add multiple pages/dashboards to a `dashboards.yaml` file, i.e. this example: https://github.com/andreasgerstmayr/fava-dashboards/blob/main/example/dashboards.yaml contains the following dashboards: Overview, Assets, Income and Expenses, Travelling and Sankey. You can copy them and call them Overview (USD), Overview (EUR), etc.

**Comment by francocalvo** [comment]
I've been doing that. I feel like been able to have many custom dashboard pages in Fava could be cool to separate some things. I'll close this now as I think this is the closest I'll get to that. Thanks for the amazing plugins!
